[workspace]
members = ["2023/day-01", "2023/day-02", "2023/day-03", "2023/day-04", "common"]
resolver = "2"

[workspace.dependencies]
common.path = "common"

[workspace.package]
edition = "2021"
authors = ["Luna Present <luna.present@outlook.com>"]
